id: A5E25A652
base_file: f8738.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:02.936649
  last_modified_at: 2022-05-30 21:55:02.936652
