id: A5E25A652
base_file: f033B.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:02.879420
  last_modified_at: 2022-05-30 21:55:02.879429
