id: A5E25A652
base_file: fB65B.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:02.973373
  last_modified_at: 2022-05-30 21:55:02.973376
