id: A5E25A652
base_file: f9FF3.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:02.962059
  last_modified_at: 2022-05-30 21:55:02.962061
