id: A5E25A652
base_file: fB725.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:02.979929
  last_modified_at: 2022-05-30 21:55:02.979932
