id: A5E25A652
base_file: f5B97.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:02.920359
  last_modified_at: 2022-05-30 21:55:02.920362
