id: A5E25A652
base_file: fFE09.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:03.009539
  last_modified_at: 2022-05-30 21:55:03.009542
