id: A5E25A652
base_file: fBC28.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:02.985822
  last_modified_at: 2022-05-30 21:55:02.985825
