id: A5E25A652
base_file: fCC2F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:02.994410
  last_modified_at: 2022-05-30 21:55:02.994413
