id: A5E25A652
base_file: fF4C4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:03.005000
  last_modified_at: 2022-05-30 21:55:03.005003
