id: A5E25A652
base_file: f2500.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:02.897602
  last_modified_at: 2022-05-30 21:55:02.897608
