id: A5E25A652
base_file: fBD35.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:02.987757
  last_modified_at: 2022-05-30 21:55:02.987760
